### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by zerkotin** [spiderworm/whats-my-weather#1]
Sorry for opening a ticket i just couldn’t find another way of contacting you.

I was wondering if you found any solution to the problem you presented in your systemjs issue to support the loading of modules in jsx.

Please contact me, you can see all my contact information On my website zerkotin.de

Thanks
Itzik.

**Comment by spiderworm** [comment]
Hi Zerkotin,

I'm afraid I did not.

Best of luck,
David
